name: Update Medium Posts

on:
  schedule:
    - cron: "0 0 */2 * *"  # Runs every 48 hours
  workflow_dispatch:

permissions:
  contents: write  # Allows workflow to commit to the README


jobs:
  update-readme:
    name: Update Medium Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@asadbukhari886"
